(function () {
  const { registerBlockVariation } =
    typeof wp.blocks !== "undefined" ? wp.blocks : {};

  wp.domReady(() => {
    if (typeof registerBlockVariation !== "undefined") {
      registerBlockVariation("kadence/testimonials", [
        {
          name: "variations-blocks-kadence-testimonials-custom-base",
          title: "Testimonials ___Base___",
          attributes: {
            uniqueID: `${Math.random().toString(36).substr(2, 6)}_c${Date.now().toString(36)}-${Math.random().toString(36).substr(2, 6)}`,
            style: "card",
            layout: "carousel",
            columns: [2,2,2,2,1,1],
            columnControl: "linked",
            columnGap: "",
            gap: [32, "", ""],
            gapUnit: "px",
            autoPlay: false,
            autoSpeed: 15000,
            transSpeed: 400,
            slidesScroll: "1",
            arrowStyle: "blackonlight",
            dotStyle: "dark",
            hAlign: "center",
            containerMaxWidth: 1920,
            containerBackground: "#edeaea",
            containerBackgroundOpacity: 1,
            containerBorder: "",
            containerBorderOpacity: 1,
            containerBorderWidth: ["", "", "", ""],
            borderStyle: [
              {
                top: ["#000000", "", ""],
                right: ["#000000", "", ""],
                bottom: ["#000000", "", ""],
                left: ["#000000", "", ""],
                unit: "px",
              },
            ],
            tabletBorderStyle: [
              {
                top: ["", "", ""],
                right: ["", "", ""],
                bottom: ["", "", ""],
                left: ["", "", ""],
                unit: "px",
              },
            ],
            mobileBorderStyle: [
              {
                top: ["", "", ""],
                right: ["", "", ""],
                bottom: ["", "", ""],
                left: ["", "", ""],
                unit: "px",
              },
            ],
            containerBorderRadius: "",
            responsiveContainerBorderRadius: ["", "", "", ""],
            tabletContainerBorderRadius: ["", "", "", ""],
            mobileContainerBorderRadius: ["", "", "", ""],
            containerBorderRadiusUnit: "px",
            containerPadding: [20, 20, 20, 20],
            testimonials: [
              {
                url: "",
                id: "",
                alt: "",
                width: "",
                height: "",
                maxWidth: "",
                subtype: "",
                media: "image",
                icon: "fas_quote-left",
                isize: 50,
                istroke: 2,
                ititle: "",
                color: "",
                title: "",
                content: "",
                name: "",
                occupation: "",
                rating: 5,
              },
            ],
            mediaStyles: [
              {
                width: 125,
                backgroundSize: "cover",
                background: "",
                backgroundOpacity: 1,
                border: "",
                borderRadius: "",
                borderWidth: ["", "", "", ""],
                padding: ["", "", "", ""],
                margin: ["", "", "", ""],
                ratio: "50",
              },
            ],
            mediaMargin: ["", "", "", ""],
            tabletMediaMargin: ["", "", "", ""],
            mobileMediaMargin: ["", "", "", ""],
            mediaMarginUnit: "px",
            mediaPadding: [0, 0, 0, 0],
            tabletMediaPadding: ["", "", "", ""],
            mobileMediaPadding: ["", "", "", ""],
            mediaPaddingUnit: "px",
            mediaBorderRadius: [100, 100, 100, 100],
            tabletMediaBorderRadius: ["", "", "", ""],
            mobileMediaBorderRadius: ["", "", "", ""],
            mediaBorderRadiusUnit: "%",
            mediaBorderStyle: [
              {
                top: ["#318e00", "", 3],
                right: ["#318e00", "", 3],
                bottom: ["#318e00", "", 3],
                left: ["#318e00", "", 3],
                unit: "px",
              },
            ],
            tabletMediaBorderStyle: [
              {
                top: ["", "", ""],
                right: ["", "", ""],
                bottom: ["", "", ""],
                left: ["", "", ""],
                unit: "px",
              },
            ],
            mobileMediaBorderStyle: [
              {
                top: ["", "", ""],
                right: ["", "", ""],
                bottom: ["", "", ""],
                left: ["", "", ""],
                unit: "px",
              },
            ],
            itemsCount: 1,
            displayMedia: true,
            displayTitle: true,
            titleFont: [
              {
                color: "",
                level: 3,
                size: ["", "", ""],
                sizetype: "px",
                lineHeight: ["", "", ""],
                linetype: "px",
                letterSpacing: "",
                textTransform: "capitalize",
                family:
                  '-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Oxygen-Sans,Ubuntu,Cantarell,"Helvetica Neue",sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"',
                google: false,
                style: "normal",
                weight: "inherit",
                variant: "",
                subset: "",
                loadGoogle: true,
                padding: ["", "", "", ""],
                margin: ["", "", "", ""],
              },
            ],
            titleMargin: ["", "", "", ""],
            tabletTitleMargin: ["", "", "", ""],
            mobileTitleMargin: ["", "", "", ""],
            titleMarginUnit: "px",
            titlePadding: ["", "", "xxs", ""],
            tabletTitlePadding: ["", "", "", ""],
            mobileTitlePadding: ["", "", "", ""],
            titlePaddingUnit: "px",
            displayContent: true,
            contentFont: [
              {
                color: "#000000",
                size: ["sm", "", ""],
                sizetype: "px",
                lineHeight: ["", "", ""],
                linetype: "px",
                letterSpacing: "",
                textTransform: "",
                family: "",
                google: "",
                style: "",
                weight: "",
                variant: "",
                subset: "",
                loadGoogle: true,
              },
            ],
            displayName: true,
            nameFont: [
              {
                color: "#000000",
                size: ["sm", "", ""],
                sizetype: "px",
                lineHeight: ["", "", ""],
                linetype: "px",
                letterSpacing: "",
                textTransform: "",
                family: "",
                google: "",
                style: "",
                weight: "bold",
                variant: "",
                subset: "",
                loadGoogle: true,
              },
            ],
            displayOccupation: true,
            occupationFont: [
              {
                color: "#000000",
                size: [15, "", ""],
                sizetype: "px",
                lineHeight: ["", "", ""],
                linetype: "px",
                letterSpacing: "",
                textTransform: "",
                family: "",
                google: "",
                style: "",
                weight: "",
                variant: "",
                subset: "",
                loadGoogle: true,
              },
            ],
            displayRating: false,
            ratingStyles: [
              {
                color: "#ffd700",
                size: 16,
                margin: ["", "", "", ""],
                iconSpacing: "",
                icon: "fas_star",
                stroke: 2,
              },
            ],
            ratingMargin: ["", "", "", ""],
            tabletRatingMargin: ["", "", "", ""],
            mobileRatingMargin: ["", "", "", ""],
            ratingMarginUnit: "px",
            ratingPadding: ["", "", "", ""],
            tabletRatingPadding: ["", "", "", ""],
            mobileRatingPadding: ["", "", "", ""],
            ratingPaddingUnit: "px",
            displayIcon: false,
            iconStyles: [
              {
                size: 30,
                margin: ["", "", "", ""],
                padding: ["", "", "", ""],
                borderWidth: ["", "", "", ""],
                borderRadius: "",
                border: "",
                borderOpacity: 1,
                color: "",
                background: "",
                backgroundOpacity: 1,
                title: "",
                icon: "fas_quote-left",
                stroke: 2,
              },
            ],
            iconBorderStyle: [
              {
                top: ["", "", ""],
                right: ["", "", ""],
                bottom: ["", "", ""],
                left: ["", "", ""],
                unit: "px",
              },
            ],
            tabletIconBorderStyle: [
              {
                top: ["", "", ""],
                right: ["", "", ""],
                bottom: ["", "", ""],
                left: ["", "", ""],
                unit: "px",
              },
            ],
            mobileIconBorderStyle: [
              {
                top: ["", "", ""],
                right: ["", "", ""],
                bottom: ["", "", ""],
                left: ["", "", ""],
                unit: "px",
              },
            ],
            iconBorderRadius: ["", "", "", ""],
            tabletIconBorderRadius: ["", "", "", ""],
            mobileIconBorderRadius: ["", "", "", ""],
            iconBorderRadiusUnit: "px",
            iconMargin: ["", "", "", ""],
            tabletIconMargin: ["", "", "", ""],
            mobileIconMargin: ["", "", "", ""],
            iconMarginUnit: "px",
            iconPadding: ["", "", "", ""],
            tabletIconPadding: ["", "", "", ""],
            mobileIconPadding: ["", "", "", ""],
            iconPaddingUnit: "px",
            displayShadow: false,
            shadow: [
              {
                color: "#000000",
                opacity: 0.2,
                spread: 0,
                blur: 14,
                hOffset: 4,
                vOffset: 2,
              },
            ],
            containerMinHeight: [200, "", ""],
            containerVAlign: "top",
            titleMinHeight: [null, "", ""],
            contentMinHeight: [67, "", ""],
            showPresets: true,
            wrapperPaddingType: "px",
            wrapperPadding: ["xxs", "xxs", "xxs", "xxs"],
            wrapperTabletPadding: ["", "", "", ""],
            wrapperMobilePadding: ["", "", "", ""],
            wrapperMargin: ["", "", "", ""],
            tabletWrapperMargin: ["", "", "", ""],
            mobileWrapperMargin: ["", "", "", ""],
            wrapperMarginUnit: "px",
            tabletContainerPadding: ["", "", "", ""],
            mobileContainerPadding: ["", "", "", ""],
            containerPaddingType: "px",
            inQueryBlock: false,
            useBlockQuoteTags: true,
            carouselType: "loop",
            kbVersion: 2,
            className:
              "variations-blocks-kadence-testimonials-custom-base is-style-image-100-100",
            metadata: {
              name: "",
            },
          },
          innerBlocks: [
            [
              "kadence/testimonial",
              {
                uniqueID: `${Math.random().toString(36).substr(2, 6)}_c${Date.now().toString(36)}-${Math.random().toString(36).substr(2, 6)}`,
                url: "../wp-content/plugins/ocade-blocks/includes/javascript-blocks-render/variations-blocks/kadence/testimonials/custom-base/custom-base-image.png",
                id: 24,
                alt: "Logo",
                width: "",
                height: "",
                maxWidth: "",
                subtype: "png",
                media: "image",
                icon: "fas_quote-left",
                isize: 50,
                tabletIsize: "",
                mobileIsize: "",
                istroke: 2,
                ititle: "",
                color: "",
                title: "Une Expérience Transformative",
                content:
                  "Depuis que j'ai découvert les services de cette entreprise, ma productivité a doublé et ma vie quotidienne s'est simplifiée. Leur support client est toujours là quand j'en ai besoin, et la qualité de leur produit est inégalée. Je recommande fortement leurs services à tous ceux qui cherchent à améliorer leur efficacité et à ajouter une valeur réelle à leur travail quotidien.",
                name: "Sophie Martin",
                occupation: "Directrice Marketing chez TechnoCorp",
                rating: 5,
                sizes: {
                  thumbnail: {
                    height: 150,
                    width: 150,
                    url: "../wp-content/plugins/ocade-blocks/includes/javascript-blocks-render/variations-blocks/kadence/testimonials/custom-base/custom-base-image.png",
                    orientation: "landscape",
                  },
                  medium: {
                    height: 300,
                    width: 300,
                    url: "../wp-content/plugins/ocade-blocks/includes/javascript-blocks-render/variations-blocks/kadence/testimonials/custom-base/custom-base-image.png",
                    orientation: "landscape",
                  },
                  "image-150x112": {
                    height: 112,
                    width: 150,
                    url: "http://batsort.docker.localhost/wp-content/uploads/2023/08/logo-150x112.png",
                    orientation: "landscape",
                  },
                  "image-150x85": {
                    height: 85,
                    width: 150,
                    url: "../wp-content/plugins/ocade-blocks/includes/javascript-blocks-render/variations-blocks/kadence/testimonials/custom-base/custom-base-image.png",
                    orientation: "landscape",
                  },
                  "image-150x267": {
                    height: 267,
                    width: 150,
                    url: "../wp-content/plugins/ocade-blocks/includes/javascript-blocks-render/variations-blocks/kadence/testimonials/custom-base/custom-base-image.png",
                    orientation: "portrait",
                  },
                  "image-150x150": {
                    height: 150,
                    width: 150,
                    url: "../wp-content/plugins/ocade-blocks/includes/javascript-blocks-render/variations-blocks/kadence/testimonials/custom-base/custom-base-image.png",
                    orientation: "landscape",
                  },
                  "image-300x225": {
                    height: 225,
                    width: 300,
                    url: "../wp-content/plugins/ocade-blocks/includes/javascript-blocks-render/variations-blocks/kadence/testimonials/custom-base/custom-base-image.png",
                    orientation: "landscape",
                  },
                  "image-300x169": {
                    height: 169,
                    width: 300,
                    url: "../wp-content/plugins/ocade-blocks/includes/javascript-blocks-render/variations-blocks/kadence/testimonials/custom-base/custom-base-image.png",
                    orientation: "landscape",
                  },
                  "image-300x553": {
                    height: 553,
                    width: 300,
                    url: "../wp-content/plugins/ocade-blocks/includes/javascript-blocks-render/variations-blocks/kadence/testimonials/custom-base/custom-base-image.png",
                    orientation: "portrait",
                  },
                  "image-300x300": {
                    height: 300,
                    width: 300,
                    url: "../wp-content/plugins/ocade-blocks/includes/javascript-blocks-render/variations-blocks/kadence/testimonials/custom-base/custom-base-image.png",
                    orientation: "landscape",
                  },
                  "image-400x300": {
                    height: 300,
                    width: 400,
                    url: "../wp-content/plugins/ocade-blocks/includes/javascript-blocks-render/variations-blocks/kadence/testimonials/custom-base/custom-base-image.png",
                    orientation: "landscape",
                  },
                  "image-400x711": {
                    height: 711,
                    width: 400,
                    url: "../wp-content/plugins/ocade-blocks/includes/javascript-blocks-render/variations-blocks/kadence/testimonials/custom-base/custom-base-image.png",
                    orientation: "portrait",
                  },
                  "image-400x400": {
                    height: 400,
                    width: 400,
                    url: "../wp-content/plugins/ocade-blocks/includes/javascript-blocks-render/variations-blocks/kadence/testimonials/custom-base/custom-base-image.png",
                    orientation: "landscape",
                  },
                  "image-700x525": {
                    height: 525,
                    width: 700,
                    url: "../wp-content/plugins/ocade-blocks/includes/javascript-blocks-render/variations-blocks/kadence/testimonials/custom-base/custom-base-image.png",
                    orientation: "landscape",
                  },
                  "image-700x393": {
                    height: 393,
                    width: 700,
                    url: "../wp-content/plugins/ocade-blocks/includes/javascript-blocks-render/variations-blocks/kadence/testimonials/custom-base/custom-base-image.png",
                    orientation: "landscape",
                  },
                  "image-700x1247": {
                    height: 1024,
                    width: 700,
                    url: "../wp-content/plugins/ocade-blocks/includes/javascript-blocks-render/variations-blocks/kadence/testimonials/custom-base/custom-base-image.png",
                    orientation: "portrait",
                  },
                  "image-700x700": {
                    height: 700,
                    width: 700,
                    url: "../wp-content/plugins/ocade-blocks/includes/javascript-blocks-render/variations-blocks/kadence/testimonials/custom-base/custom-base-image.png",
                    orientation: "landscape",
                  },
                  "image-1024x768": {
                    height: 768,
                    width: 1024,
                    url: "../wp-content/plugins/ocade-blocks/includes/javascript-blocks-render/variations-blocks/kadence/testimonials/custom-base/custom-base-image.png",
                    orientation: "landscape",
                  },
                  "image-1024x576": {
                    height: 576,
                    width: 1024,
                    url: "../wp-content/plugins/ocade-blocks/includes/javascript-blocks-render/variations-blocks/kadence/testimonials/custom-base/custom-base-image.png",
                    orientation: "landscape",
                  },
                  full: {
                    url: "../wp-content/plugins/ocade-blocks/includes/javascript-blocks-render/variations-blocks/kadence/testimonials/custom-base/custom-base-image.png",
                    height: 1024,
                    width: 1024,
                    orientation: "landscape",
                  },
                },
                inQueryBlock: false,
                useBlockQuoteTags: true,
                metadata: {
                  name: "",
                },
              },
              [],
            ],
            [
              "kadence/testimonial",
              {
                uniqueID: `${Math.random().toString(36).substr(2, 6)}_c${Date.now().toString(36)}-${Math.random().toString(36).substr(2, 6)}`,
                url: "../wp-content/plugins/ocade-blocks/includes/javascript-blocks-render/variations-blocks/kadence/testimonials/custom-base/custom-base-image.png",
                id: 25,
                alt: "Logo",
                width: "",
                height: "",
                maxWidth: "",
                subtype: "png",
                media: "image",
                icon: "fas_quote-left",
                isize: 50,
                tabletIsize: "",
                mobileIsize: "",
                istroke: 2,
                ititle: "",
                color: "",
                title: "Un Service Incomparable !",
                content:
                  "Depuis que nous avons commencé à travailler avec cette équipe, notre site web a connu une transformation incroyable. Leur expertise en matière de design et de développement a dépassé toutes nos attentes. Nous recommandons vivement leurs services à toute entreprise cherchant à améliorer sa présence en ligne.",
                name: "Jean Dupont",
                occupation: "Directeur Marketing chez TechCorp",
                rating: 5,
                sizes: {
                  thumbnail: {
                    height: 150,
                    width: 150,
                    url: "../wp-content/plugins/ocade-blocks/includes/javascript-blocks-render/variations-blocks/kadence/testimonials/custom-base/custom-base-image.png",
                    orientation: "landscape",
                  },
                  medium: {
                    height: 300,
                    width: 300,
                    url: "../wp-content/plugins/ocade-blocks/includes/javascript-blocks-render/variations-blocks/kadence/testimonials/custom-base/custom-base-image.png",
                    orientation: "landscape",
                  },
                  "image-150x112": {
                    height: 112,
                    width: 150,
                    url: "../wp-content/plugins/ocade-blocks/includes/javascript-blocks-render/variations-blocks/kadence/testimonials/custom-base/custom-base-image.png",
                    orientation: "landscape",
                  },
                  "image-150x85": {
                    height: 85,
                    width: 150,
                    url: "../wp-content/plugins/ocade-blocks/includes/javascript-blocks-render/variations-blocks/kadence/testimonials/custom-base/custom-base-image.png",
                    orientation: "landscape",
                  },
                  "image-150x267": {
                    height: 267,
                    width: 150,
                    url: "../wp-content/plugins/ocade-blocks/includes/javascript-blocks-render/variations-blocks/kadence/testimonials/custom-base/custom-base-image.png",
                    orientation: "portrait",
                  },
                  "image-150x150": {
                    height: 150,
                    width: 150,
                    url: "../wp-content/plugins/ocade-blocks/includes/javascript-blocks-render/variations-blocks/kadence/testimonials/custom-base/custom-base-image.png",
                    orientation: "landscape",
                  },
                  "image-300x225": {
                    height: 225,
                    width: 300,
                    url: "../wp-content/plugins/ocade-blocks/includes/javascript-blocks-render/variations-blocks/kadence/testimonials/custom-base/custom-base-image.png",
                    orientation: "landscape",
                  },
                  "image-300x169": {
                    height: 169,
                    width: 300,
                    url: "../wp-content/plugins/ocade-blocks/includes/javascript-blocks-render/variations-blocks/kadence/testimonials/custom-base/custom-base-image.png",
                    orientation: "landscape",
                  },
                  "image-300x553": {
                    height: 553,
                    width: 300,
                    url: "../wp-content/plugins/ocade-blocks/includes/javascript-blocks-render/variations-blocks/kadence/testimonials/custom-base/custom-base-image.png",
                    orientation: "portrait",
                  },
                  "image-300x300": {
                    height: 300,
                    width: 300,
                    url: "../wp-content/plugins/ocade-blocks/includes/javascript-blocks-render/variations-blocks/kadence/testimonials/custom-base/custom-base-image.png",
                    orientation: "landscape",
                  },
                  "image-400x300": {
                    height: 300,
                    width: 400,
                    url: "../wp-content/plugins/ocade-blocks/includes/javascript-blocks-render/variations-blocks/kadence/testimonials/custom-base/custom-base-image.png",
                    orientation: "landscape",
                  },
                  "image-400x711": {
                    height: 711,
                    width: 400,
                    url: "../wp-content/plugins/ocade-blocks/includes/javascript-blocks-render/variations-blocks/kadence/testimonials/custom-base/custom-base-image.png",
                    orientation: "portrait",
                  },
                  "image-400x400": {
                    height: 400,
                    width: 400,
                    url: "../wp-content/plugins/ocade-blocks/includes/javascript-blocks-render/variations-blocks/kadence/testimonials/custom-base/custom-base-image.png",
                    orientation: "landscape",
                  },
                  "image-700x525": {
                    height: 525,
                    width: 700,
                    url: "../wp-content/plugins/ocade-blocks/includes/javascript-blocks-render/variations-blocks/kadence/testimonials/custom-base/custom-base-image.png",
                    orientation: "landscape",
                  },
                  "image-700x393": {
                    height: 393,
                    width: 700,
                    url: "../wp-content/plugins/ocade-blocks/includes/javascript-blocks-render/variations-blocks/kadence/testimonials/custom-base/custom-base-image.png",
                    orientation: "landscape",
                  },
                  "image-700x1247": {
                    height: 1023,
                    width: 700,
                    url: "../wp-content/plugins/ocade-blocks/includes/javascript-blocks-render/variations-blocks/kadence/testimonials/custom-base/custom-base-image.png",
                    orientation: "portrait",
                  },
                  "image-700x700": {
                    height: 700,
                    width: 700,
                    url: "../wp-content/plugins/ocade-blocks/includes/javascript-blocks-render/variations-blocks/kadence/testimonials/custom-base/custom-base-image.png",
                    orientation: "landscape",
                  },
                  "image-1024x768": {
                    height: 768,
                    width: 1023,
                    url: "../wp-content/plugins/ocade-blocks/includes/javascript-blocks-render/variations-blocks/kadence/testimonials/custom-base/custom-base-image.png",
                    orientation: "landscape",
                  },
                  "image-1024x576": {
                    height: 576,
                    width: 1023,
                    url: "../wp-content/plugins/ocade-blocks/includes/javascript-blocks-render/variations-blocks/kadence/testimonials/custom-base/custom-base-image.png",
                    orientation: "landscape",
                  },
                  full: {
                    url: "../wp-content/plugins/ocade-blocks/includes/javascript-blocks-render/variations-blocks/kadence/testimonials/custom-base/custom-base-image.png",
                    height: 1023,
                    width: 1023,
                    orientation: "landscape",
                  },
                },
                inQueryBlock: false,
                useBlockQuoteTags: true,
                metadata: {
                  name: "",
                },
              },
              [],
            ],
            [
              "kadence/testimonial",
              {
                uniqueID: "159_800ceb-ee",
                url: "../wp-content/plugins/ocade-blocks/includes/javascript-blocks-render/variations-blocks/kadence/testimonials/custom-base/custom-base-image.png",
                id: 25,
                alt: "Logo",
                width: "",
                height: "",
                maxWidth: "",
                subtype: "png",
                media: "image",
                icon: "fas_quote-left",
                isize: 50,
                tabletIsize: "",
                mobileIsize: "",
                istroke: 2,
                ititle: "",
                color: "",
                title: "Collaboration Efficace et Professionnelle",
                content:
                  "La collaboration avec cette entreprise a été une expérience incroyable. Leur compréhension de nos besoins et leur capacité à les traduire en solutions web efficaces nous ont impressionnés. Nous sommes plus que satisfaits des résultats et continuerons à travailler avec eux à l'avenir.",
                name: "Marie Durand",
                occupation: "Chef de Projet chez DesignFlow",
                rating: 5,
                sizes: {
                  thumbnail: {
                    height: 150,
                    width: 150,
                    url: "http://batsort.docker.localhost/wp-content/uploads/2023/08/cropped-logo-150x150.png",
                    orientation: "landscape",
                  },
                  medium: {
                    height: 300,
                    width: 300,
                    url: "http://batsort.docker.localhost/wp-content/uploads/2023/08/cropped-logo-300x300.png",
                    orientation: "landscape",
                  },
                  "image-150x112": {
                    height: 112,
                    width: 150,
                    url: "http://batsort.docker.localhost/wp-content/uploads/2023/08/cropped-logo-150x112.png",
                    orientation: "landscape",
                  },
                  "image-150x85": {
                    height: 85,
                    width: 150,
                    url: "http://batsort.docker.localhost/wp-content/uploads/2023/08/cropped-logo-150x85.png",
                    orientation: "landscape",
                  },
                  "image-150x267": {
                    height: 267,
                    width: 150,
                    url: "http://batsort.docker.localhost/wp-content/uploads/2023/08/cropped-logo-150x267.png",
                    orientation: "portrait",
                  },
                  "image-150x150": {
                    height: 150,
                    width: 150,
                    url: "http://batsort.docker.localhost/wp-content/uploads/2023/08/cropped-logo-150x150.png",
                    orientation: "landscape",
                  },
                  "image-300x225": {
                    height: 225,
                    width: 300,
                    url: "http://batsort.docker.localhost/wp-content/uploads/2023/08/cropped-logo-300x225.png",
                    orientation: "landscape",
                  },
                  "image-300x169": {
                    height: 169,
                    width: 300,
                    url: "http://batsort.docker.localhost/wp-content/uploads/2023/08/cropped-logo-300x169.png",
                    orientation: "landscape",
                  },
                  "image-300x553": {
                    height: 553,
                    width: 300,
                    url: "http://batsort.docker.localhost/wp-content/uploads/2023/08/cropped-logo-300x553.png",
                    orientation: "portrait",
                  },
                  "image-300x300": {
                    height: 300,
                    width: 300,
                    url: "http://batsort.docker.localhost/wp-content/uploads/2023/08/cropped-logo-300x300.png",
                    orientation: "landscape",
                  },
                  "image-400x300": {
                    height: 300,
                    width: 400,
                    url: "http://batsort.docker.localhost/wp-content/uploads/2023/08/cropped-logo-400x300.png",
                    orientation: "landscape",
                  },
                  "image-400x711": {
                    height: 711,
                    width: 400,
                    url: "http://batsort.docker.localhost/wp-content/uploads/2023/08/cropped-logo-400x711.png",
                    orientation: "portrait",
                  },
                  "image-400x400": {
                    height: 400,
                    width: 400,
                    url: "http://batsort.docker.localhost/wp-content/uploads/2023/08/cropped-logo-400x400.png",
                    orientation: "landscape",
                  },
                  "image-700x525": {
                    height: 525,
                    width: 700,
                    url: "http://batsort.docker.localhost/wp-content/uploads/2023/08/cropped-logo-700x525.png",
                    orientation: "landscape",
                  },
                  "image-700x393": {
                    height: 393,
                    width: 700,
                    url: "http://batsort.docker.localhost/wp-content/uploads/2023/08/cropped-logo-700x393.png",
                    orientation: "landscape",
                  },
                  "image-700x1247": {
                    height: 1023,
                    width: 700,
                    url: "http://batsort.docker.localhost/wp-content/uploads/2023/08/cropped-logo-700x1023.png",
                    orientation: "portrait",
                  },
                  "image-700x700": {
                    height: 700,
                    width: 700,
                    url: "http://batsort.docker.localhost/wp-content/uploads/2023/08/cropped-logo-700x700.png",
                    orientation: "landscape",
                  },
                  "image-1024x768": {
                    height: 768,
                    width: 1023,
                    url: "http://batsort.docker.localhost/wp-content/uploads/2023/08/cropped-logo-1023x768.png",
                    orientation: "landscape",
                  },
                  "image-1024x576": {
                    height: 576,
                    width: 1023,
                    url: "http://batsort.docker.localhost/wp-content/uploads/2023/08/cropped-logo-1023x576.png",
                    orientation: "landscape",
                  },
                  full: {
                    url: "http://batsort.docker.localhost/wp-content/uploads/2023/08/cropped-logo.webp",
                    height: 1023,
                    width: 1023,
                    orientation: "landscape",
                  },
                },
                inQueryBlock: false,
                useBlockQuoteTags: true,
                metadata: {
                  name: "",
                },
              },
              [],
            ],
          ],
          example: {
            innerBlocks: [
              {
                name: "core/image",
                attributes: {
                  url: "../wp-content/plugins/ocade-blocks/includes/javascript-blocks-render/variations-blocks/kadence/testimonials/custom-base/custom-base.png"
                },
              }
            ],
          },
        },
      ]);
    }
  });
})();
